---
- name: Symlink resolv.conf to systemd DNS stub file
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    path: /etc/resolv.conf
    state: link
    force: yes
  notify: Restart systemd-resolved

- name: Create resolved.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: "0755"

- name: Check existing configuration files
  ansible.builtin.find:
    paths: /etc/systemd/resolved.conf.d
    patterns: "*.conf"
  when: catena_resolved_cleanup
  register: existing_config

- name: Remove existing configuration files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ existing_config.files }}"
  when: catena_resolved_cleanup
  notify: Restart systemd-resolved

- name: Generate name resolution configuration files
  ansible.builtin.template:
    src: resolved_config.j2
    dest: "/etc/systemd/resolved.conf.d/{{ item.name }}.conf"
    owner: root
    group: systemd-resolve
    mode: "0644"
  vars:
    - current_item: "{{ item.options }}"
  loop: "{{ catena_resolved }}"
  notify: Restart systemd-resolved
